### ISSUE TITLE
Option to disable specific parse rules?

### ISSUE THREAD

**Issue by subvertallchris** [berkmancenter/namae#16]
Hello! It would be very helpful if specific rules could be disabled entirely. Similar to https://github.com/berkmancenter/namae/issues/12, I'm getting `nil` back for someone whose last name is Herr. Our names are stricly some combination of first/last, no titles or appellations, so it would be extremely helpful if we could just disable some rules entirely.

**Comment by subvertallchris** [comment]
Alternatively, being able to set custom global options could achieve the same result and make the gem more powerful. I could give it an empty regex for appellation, or maybe I have custom titles that I want to match.

**Comment by inukshuk** [comment]
Thanks for reporting!

You can adjust the parser options in `Namae::Parser.instance.options`.

We could probably adjust the [consume_word](https://github.com/berkmancenter/namae/blob/master/lib/namae/parser.y#L201) method to consume titles and appellations only in certain conditions. Will take a look!

**Comment by inukshuk** [comment]
OK I updated the lexer to accept appellations only as the first word in 0.11.0. This should fix the last name `Herr` issue. I did not adjust title matching, because titles could occur elsewhere in a name -- we'd have to give some thought to defining a useful rule there. In any case, like I said, you can just adjust the patterns to your needs to make sure titles are not matched for example.
