### ISSUE TITLE
Namae isn't thread safe

### ISSUE THREAD

**Issue by hackling** [berkmancenter/namae#22]
This causes issues, especially if you are using a threaded webserver like puma https://github.com/puma/puma

The following code reproduces the error:
``` ruby
require 'namae'

name1_s = "Foo Bar"
name2_s = "Baz"

name1 = Namae.parse(name1_s).first
r1 = [name1.given, name1.family]

name2 = Namae.parse(name2_s).first
r2 = [name2.given, name2.family]

$issues = []

def verify(str, expected)
  name = Namae.parse(str).first
  if name == nil
    $issues << {error: "Parser returned nil"}
    return
  end

  result = [name.given, name.family]

  if result != expected
    $issues << {
      name: str,
      expected: expected,
      result: result,
    }
  end
end

N = 10_000

[[name1_s, r1], [name2_s, r2]].map do |str, expected|
  Thread.new do
    N.times do
      verify(str, expected)
    end
  end
end.each(&:join)

require "pp"
pp $issues
```

Example output:
```
[{:name=>"Baz", :expected=>["Baz", nil], :result=>["Foo", "Bar"]},
 {:name=>"Foo Bar", :expected=>["Foo", "Bar"], :result=>["Baz", nil]},
 {:name=>"Baz", :expected=>["Baz", nil], :result=>[" Ba", "r"]},
 {:error=>"Parser returned nil"}]
```

```
[{:name=>"Foo Bar", :expected=>["Foo", "Bar"], :result=>["Baz", nil]},
 {:name=>"Baz", :expected=>["Baz", nil], :result=>["Bar", nil]},
 {:name=>"Foo Bar", :expected=>["Foo", "Bar"], :result=>["Foo", "Baz"]},
 {:error=>"Parser returned nil"},
 {:error=>"Parser returned nil"},
 {:name=>"Foo Bar", :expected=>["Foo", "Bar"], :result=>["Foo", nil]}]
```

Presumably this is because it uses a stateful singleton.

https://github.com/berkmancenter/namae/blob/6b0f69ad36746a4ac21b394aa3667f560c2b561c/lib/namae/parser.rb#L17

**Comment by inukshuk** [comment]
I've finally had time to look into this. I made a couple of changes which were long overdue and that should address the issue:

* No more `Singleton`, meaning you can just create your own parser instances https://github.com/berkmancenter/namae/commit/286c86374d49b9cec613f05ff84827b9cdff5b61
* Do not re-use the same string scanner instance every time (less scary!) https://github.com/berkmancenter/namae/commit/27b32647c5cef78f4f44c589b0378571f424ab6d
* Move parser default options to class instance (still global!) and the default parser into thread local https://github.com/berkmancenter/namae/commit/f5a829b35509c029dc19865d8c469d46ec425d1d

I've added your script above to our tests; it returns no errors for me now.

The parser defaults are still global, but I think that's OK, because it means you can easily change the defaults for all new threads. The default parser itself is thread-local (and so are its instance options). If that is still too scary, everyone is free to just manage their own instances and never use the top-level methods (in that case not default parser will be created).

What do you think? If you're happy with this, I'll push 1.0.0 to Ruby Gems.

Thanks for contributing!
