### ISSUE TITLE
Parsing breaks when both nick/appellation and suffix are present

### ISSUE THREAD

**Issue by burmashave** [berkmancenter/namae#7]
Namae.parse 'Yukihiro "Matz" Matsumoto'
    => [#<Name family="Matsumoto" given="Yukihiro" nick="Matz">] 
Namae.parse 'Yukihiro Matsumoto, Jr.'
    => [#<Name family="Matsumoto" given="Yukihiro" suffix="Jr.">] 
Namae.parse 'Yukihiro "Lil Matz" Matsumoto, Jr.'
    => [] 

Namae.parse 'Ms. Sofia Kovaleskaya'          
    => [#<Name family="Kovaleskaya" given="Sofia" appellation="Ms.">] 
Namae.parse 'Ms. Sofia Kovaleskaya, III'
    => []

**Comment by burmashave** [comment]
Freaking markdown. That should be:
```
Namae.parse 'Yukihiro "Matz" Matsumoto'
    => [#<Name family="Matsumoto" given="Yukihiro" nick="Matz">] 
Namae.parse 'Yukihiro Matsumoto, Jr.'
    => [#<Name family="Matsumoto" given="Yukihiro" suffix="Jr.">] 
Namae.parse 'Yukihiro "Lil Matz" Matsumoto, Jr.'
    => [] 

Namae.parse 'Ms. Sofia Kovaleskaya'          
    => [#<Name family="Kovaleskaya" given="Sofia" appellation="Ms.">] 
Namae.parse 'Ms. Sofia Kovaleskaya, III'
    => [] 
```

**Comment by inukshuk** [comment]
Namae is pretty picky about commas, because they can be used both to separate parts of a name and names in a list. The nickname examples are using what we call 'display order' (i.e., first name last name with no commas) -- using this syntax you need to omit the comma before the suffix. Having said that, the nickname pattern did not support suffixes previously, but this should now be supported in version 0.9.3. That is:

    irb(main):002:0> Namae::Version::STRING
    => "0.9.3"
    irb(main):003:0> Namae.parse 'Ms. Sofia Kovaleskaya III'                        => [#<Name family="Kovaleskaya" given="Sofia" suffix="III" appellation="Ms.">]
